[platformio]
src_dir = src

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit BMP5xx Library
    adafruit/Adafruit SHTC3 Library
    adafruit/Adafruit Unified Sensor
    bblanchon/ArduinoJson
    h2zero/NimBLE-Arduino
    jgromes/RadioLib
    mikalhart/TinyGPSPlus
    olikraus/U8g2
    solderedelectronics/Soldered PCF85063A RTC Library

[env:native]
platform = native
test_framework = googletest
test_build_src = yes
test_ignore = test_device
lib_compat_mode = off
build_src_filter = -<*> +<Vario.cpp> +<Gps.cpp>
build_flags =
    -std=gnu++17
    -I$PROJECT_DIR/test/test_native/stubs
lib_deps =
    mikalhart/TinyGPSPlus
    