#pragma once
// AUTO-GENERATED by generate_header.py -- do not hand-edit.
// Regenerate if the vocabulary changes so VOICE/*.PCM on the SD card and
// this enum never drift apart. Each entry is stored at /VOICE/V###.PCM
// on the SD card, where ### is this enum's numeric value zero-padded to 3
// digits (see voiceClipFilename() in VoiceAlert.cpp).

enum VoiceClipId {
  VOICE_NUM_0 = 0,  // "zero"
  VOICE_NUM_1 = 1,  // "one"
  VOICE_NUM_2 = 2,  // "two"
  VOICE_NUM_3 = 3,  // "three"
  VOICE_NUM_4 = 4,  // "four"
  VOICE_NUM_5 = 5,  // "five"
  VOICE_NUM_6 = 6,  // "six"
  VOICE_NUM_7 = 7,  // "seven"
  VOICE_NUM_8 = 8,  // "eight"
  VOICE_NUM_9 = 9,  // "nine"
  VOICE_NUM_10 = 10,  // "ten"
  VOICE_NUM_11 = 11,  // "eleven"
  VOICE_NUM_12 = 12,  // "twelve"
  VOICE_NUM_13 = 13,  // "thirteen"
  VOICE_NUM_14 = 14,  // "fourteen"
  VOICE_NUM_15 = 15,  // "fifteen"
  VOICE_NUM_16 = 16,  // "sixteen"
  VOICE_NUM_17 = 17,  // "seventeen"
  VOICE_NUM_18 = 18,  // "eighteen"
  VOICE_NUM_19 = 19,  // "nineteen"
  VOICE_NUM_20 = 20,  // "twenty"
  VOICE_NUM_30 = 21,  // "thirty"
  VOICE_NUM_40 = 22,  // "forty"
  VOICE_NUM_50 = 23,  // "fifty"
  VOICE_NUM_60 = 24,  // "sixty"
  VOICE_NUM_70 = 25,  // "seventy"
  VOICE_NUM_80 = 26,  // "eighty"
  VOICE_NUM_90 = 27,  // "ninety"
  VOICE_NUM_HUNDRED = 28,  // "hundred"
  VOICE_NUM_THOUSAND = 29,  // "thousand"
  VOICE_CLOCK_1 = 30,  // "one o'clock"
  VOICE_CLOCK_2 = 31,  // "two o'clock"
  VOICE_CLOCK_3 = 32,  // "three o'clock"
  VOICE_CLOCK_4 = 33,  // "four o'clock"
  VOICE_CLOCK_5 = 34,  // "five o'clock"
  VOICE_CLOCK_6 = 35,  // "six o'clock"
  VOICE_CLOCK_7 = 36,  // "seven o'clock"
  VOICE_CLOCK_8 = 37,  // "eight o'clock"
  VOICE_CLOCK_9 = 38,  // "nine o'clock"
  VOICE_CLOCK_10 = 39,  // "ten o'clock"
  VOICE_CLOCK_11 = 40,  // "eleven o'clock"
  VOICE_CLOCK_12 = 41,  // "twelve o'clock"
  VOICE_COMPASS_NORTH = 42,  // "north"
  VOICE_COMPASS_NORTH_EAST = 43,  // "north east"
  VOICE_COMPASS_EAST = 44,  // "east"
  VOICE_COMPASS_SOUTH_EAST = 45,  // "south east"
  VOICE_COMPASS_SOUTH = 46,  // "south"
  VOICE_COMPASS_SOUTH_WEST = 47,  // "south west"
  VOICE_COMPASS_WEST = 48,  // "west"
  VOICE_COMPASS_NORTH_WEST = 49,  // "north west"
  VOICE_PHRASE_AIRCRAFT_ON_YOUR = 50,  // "Aircraft on your"
  VOICE_PHRASE_FLYING = 51,  // "flying"
  VOICE_PHRASE_AT = 52,  // "at"
  VOICE_PHRASE_FEET = 53,  // "feet"
  VOICE_PHRASE_FEET_ABOVE_YOU = 54,  // "feet above you"
  VOICE_PHRASE_FEET_BELOW_YOU = 55,  // "feet below you"
  VOICE_PHRASE_AND_IS = 56,  // "and is"
  VOICE_PHRASE_METERS_AWAY = 57,  // "meters away"
  VOICE_PHRASE_KILOMETERS_AWAY = 58,  // "kilometers away"
  VOICE_PHRASE_HEADING_UNKNOWN = 59,  // "heading unknown"
  VOICE_CLIP_COUNT = 60
};

// Lookup tables for the number-to-clip-sequence composer (VoiceAlert.cpp).
static const VoiceClipId VOICE_ONES[20] = {
  VOICE_NUM_0, VOICE_NUM_1, VOICE_NUM_2, VOICE_NUM_3, VOICE_NUM_4, VOICE_NUM_5, VOICE_NUM_6, VOICE_NUM_7, VOICE_NUM_8, VOICE_NUM_9, VOICE_NUM_10, VOICE_NUM_11, VOICE_NUM_12, VOICE_NUM_13, VOICE_NUM_14, VOICE_NUM_15, VOICE_NUM_16, VOICE_NUM_17, VOICE_NUM_18, VOICE_NUM_19
};
// Index 0 unused (there's no VOICE_NUM_10-multiple below 20); index 2 = 20, ... index 9 = 90.
static const VoiceClipId VOICE_TENS[10] = {
  VOICE_NUM_0, VOICE_NUM_0, VOICE_NUM_20, VOICE_NUM_30, VOICE_NUM_40, VOICE_NUM_50, VOICE_NUM_60, VOICE_NUM_70, VOICE_NUM_80, VOICE_NUM_90  // [0] and [1] unused placeholders
};

static const VoiceClipId VOICE_CLOCK[13] = {
  VOICE_CLOCK_1,  // [0] unused placeholder (clock positions are 1-12)
  VOICE_CLOCK_1, VOICE_CLOCK_2, VOICE_CLOCK_3, VOICE_CLOCK_4, VOICE_CLOCK_5, VOICE_CLOCK_6, VOICE_CLOCK_7, VOICE_CLOCK_8, VOICE_CLOCK_9, VOICE_CLOCK_10, VOICE_CLOCK_11, VOICE_CLOCK_12
};

// Indexed by the same 8-way compass order getCompassDirection() uses:
// N, NE, E, SE, S, SW, W, NW.
static const VoiceClipId VOICE_COMPASS[8] = {
  VOICE_COMPASS_NORTH, VOICE_COMPASS_NORTH_EAST, VOICE_COMPASS_EAST, VOICE_COMPASS_SOUTH_EAST, VOICE_COMPASS_SOUTH, VOICE_COMPASS_SOUTH_WEST, VOICE_COMPASS_WEST, VOICE_COMPASS_NORTH_WEST
};

#define VOICE_CLIP_SAMPLE_RATE 16000
